{
    "name": "Deploy website",
    "on": {
        "schedule": {
            "cron": "6 * * * *", # hourly
        },
    },
    "jobs": {
        "deploy": {
            "name": "Build and deploy",
            "timeout-minutes": 5,
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "name": "Checkout website repository",
                    "uses": "actions/checkout@v1",
                    "with": {
                        "fetch-depth": 1,
                        "ref": "gh-pages",
                        "path": "robloxapi.github.io/ref",
                    },
                },
                {
                    "name": "Checkout documentation repository",
                    "uses": "actions/checkout@v1",
                    "with": {
                        "repository": "RobloxAPI/doc",
                        "fetch-depth": 1,
                        "ref": "master",
                        "path": "doc",
                    },
                },
                {
                    "name": "Checkout executable repository",
                    "uses": "actions/checkout@v1",
                    "with": {
                        "repository": "RobloxAPI/rbxapiref",
                        "fetch-depth": 1,
                        "ref": "master",
                        "path": "rbxapiref",
                    },
                },
                {
                    "name": "Print environment",
                    "run": "printenv",
                },
                {
                    "name": "List files",
                    "run": "ls -AlR ~/work",
                },
                {
                    "name": "Generate module",
                    "run": "
                        cd $GITHUB_WORKSPACE/../../rbxapiref &&
                        go mod init github.com/robloxapi/rbxapiref
                    ",
                },
                {
                    "name": "Get dependencies",
                    "run": "
                        cd $GITHUB_WORKSPACE/../../rbxapiref &&
                        go get -v -d ./...
                    ",
                },
                {
                    "name": "Compile executable",
                    "run": "
                        cd $GITHUB_WORKSPACE/../../rbxapiref &&
                        go build -v .
                    ",
                },
                {
                    "name": "Rebuild website",
                    "run": "$GITHUB_WORKSPACE/../../rbxapiref/rbxapiref -s .github/settings.json",
                },
                # {
                #     "name": "Commit and push website",
                #     "env": {
                #         "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}",
                #     },
                #     "run": "
                #         git config user.email 'actions@github.com' &&
                #         git config user.name 'GitHub Actions' &&
                #         git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git &&
                #         git add -A &&
                #         git commit -m 'Update reference.' &&
                #         git push origin gh-pages &&
                #         curl -u Anaminus:$GITHUB_TOKEN -X POST https://api.github.com/repos/RobloxAPI/ref/pages/builds -H 'Accept: application/vnd.github.mister-fantastic-preview+json' ||
                #         true
                #     ",
                # },
                {
                    "name": "Force redeploy of website",
                    "env": {
                        "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}",
                    },
                    "run": "curl -u Anaminus:$GITHUB_TOKEN -X POST https://api.github.com/repos/RobloxAPI/ref/pages/builds -H 'Accept: application/vnd.github.mister-fantastic-preview+json'",
                },
            ],
        },
    },
}
